#!/bin/sh

set -eu

if [ "$LOCAL" ]; then
  set -x
fi

builddirs() {
  dirname $(find main/${PACKAGE:-*}/ -type f -name APKBUILD)
}

prepare() {
  cd /home/builder/aports
  mkdir -p "$REPODEST" /home/builder/.abuild
  abuild-apk update
  [ "$RSA_PRIVATE_KEY" ] && {
    echo -e "$RSA_PRIVATE_KEY" > "/home/builder/.abuild/$RSA_PRIVATE_KEY_NAME"
    export PACKAGER_PRIVKEY="/home/builder/.abuild/$RSA_PRIVATE_KEY_NAME"
  }
}

sync() {
  if [ "$LOCAL" ]; then
    echo ">>> s3: Running in local mode, will not sync"
    return 0
  fi

  case "$1" in
    up)
      [ "$AWS_ACCESS_KEY_ID" ] && [ "$AWS_SECRET_ACCESS_KEY" ] && {
        aws s3 sync $REPODEST $REPOREMOTE
      } || echo ">>> s3: No AWS credentials not running sync"
      ;;
    down)
      aws s3 sync --no-sign-request $REPOREMOTE $REPODEST
      ;;
  esac
}

main() {
  prepare
  sync down
  for dir in $(builddirs)
  do
    (cd $dir && abuild -r -k "$@") || exit 1
  done
  sync up
}

main "$@"
