#!/bin/sh

set -eu

builddirs() {
  dirname $(find main -path "*/APKBUILD" -type f)
}

prepare() {
  cd /home/builder/aports
  mkdir -p "$REPODEST" /home/builder/.abuild
  abuild-apk update
  [ "$RSA_PRIVATE_KEY" ] && {
    echo -e "$RSA_PRIVATE_KEY" > "/home/builder/.abuild/$RSA_PRIVATE_KEY_NAME"
    export PACKAGER_PRIVKEY="/home/builder/.abuild/$RSA_PRIVATE_KEY_NAME"
  }
}

main() {
  prepare
  for dir in $(builddirs)
  do
    (cd $dir && abuild -r "$@") || exit 1
  done
}

main "$@"
