#!/bin/bash

set -e

docker build -t assemblyline/abuild script/.

mkdir -p repo

docker run \
  --rm \
  -e RSA_PRIVATE_KEY="$(cat $PWD/keys/alpine-devel@a10e.org-58886ad0.rsa)" \
  -e RSA_PRIVATE_KEY_NAME="alpine-devel@a10e.org-58886ad0.rsa" \
  -e USER_ID=`id -u $USER` \
  -v "$PWD:/home/builder/aports" \
  -v "$PWD/repo:/packages" \
  -v "$PWD/keys/alpine-devel@a10e.org-58886ad0.rsa.pub:/etc/apk/keys/alpine-devel@a10e.org-58886ad0.rsa.pub" \
  assemblyline/abuild "$@"
